apiVersion: k8splugin.io/v1alpha1
kind: ResourceBundleState
metadata:
  creationTimestamp: null
  labels:
    emco/deployment-id: 6159385080388311192-collectd
  name: 6159385080388311192-collectd
spec:
  selector:
    matchLabels:
      emco/deployment-id: 6159385080388311192-collectd
status:
  ready: false
  resourceCount: 0
