apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: app100ns
  namespace: myns
spec:
  interval: 5m0s
  path: ./clusters/10309/context/100
  prune: true
  sourceRef:
    kind: GitRepository
    name: app100ns
  targetNamespace: myns
