apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  creationTimestamp: null
  name: "729354321459352411"
  namespace: default
spec:
  interval: 1s
  ref:
    branch: main
  url: https://github.com/ritusood/test
status: {}
