apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  creationTimestamp: null
  name: kcust8024763025792722674
  namespace: default
spec:
  interval: 5m0s
  path: clusters/provider1flux+cluster2/context/8024763025792722674
  prune: true
  sourceRef:
    kind: GitRepository
    name: "8024763025792722674"
  targetNamespace: default
status: {}
