apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  creationTimestamp: null
  name: kcust5090649947457881962
  namespace: default
spec:
  interval: 5m0s
  path: clusters/provider1flux+cluster2/context/5090649947457881962
  prune: true
  sourceRef:
    kind: GitRepository
    name: "5090649947457881962"
  targetNamespace: default
status: {}
