apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  creationTimestamp: null
  name: kcust6271645197154662872
  namespace: default
spec:
  interval: 5m0s
  path: clusters/provider1flux+cluster2/context/6271645197154662872
  prune: true
  sourceRef:
    kind: GitRepository
    name: "6271645197154662872"
  targetNamespace: default
status: {}
