apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  creationTimestamp: null
  name: kcust4901938971766747040
  namespace: default
spec:
  interval: 5m0s
  path: clusters/provider1flux+cluster2/context/4901938971766747040
  prune: true
  sourceRef:
    kind: GitRepository
    name: "4901938971766747040"
  targetNamespace: default
status: {}
