apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  creationTimestamp: null
  name: kcust8368102856732556558
  namespace: default
spec:
  interval: 5m0s
  path: clusters/provider1flux+cluster2/context/8368102856732556558
  prune: true
  sourceRef:
    kind: GitRepository
    name: "8368102856732556558"
  targetNamespace: default
status: {}
