apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  creationTimestamp: null
  name: kcust2144807127684225031
  namespace: default
spec:
  interval: 5m0s
  path: clusters/provider1flux+cluster2/context/2144807127684225031
  prune: true
  sourceRef:
    kind: GitRepository
    name: "2144807127684225031"
  targetNamespace: default
status: {}
