apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  creationTimestamp: null
  name: kcust6169915910828344722
  namespace: default
spec:
  interval: 5m0s
  path: clusters/provider1flux+cluster2/context/6169915910828344722
  prune: true
  sourceRef:
    kind: GitRepository
    name: "6169915910828344722"
  targetNamespace: default
status: {}
