apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  creationTimestamp: null
  name: kcust7380188690906925398
  namespace: default
spec:
  interval: 5m0s
  path: clusters/provider1flux+cluster2/context/7380188690906925398
  prune: true
  sourceRef:
    kind: GitRepository
    name: "7380188690906925398"
  targetNamespace: default
status: {}
