apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  creationTimestamp: null
  name: "1767208237073858560"
  namespace: default
spec:
  interval: 30s
  ref:
    branch: main
  url: https://github.com/ritusood/test
status: {}
