apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  creationTimestamp: null
  name: kcust1930740063454277023
  namespace: default
spec:
  interval: 5m0s
  path: clusters/provider10+cluster2/context/1930740063454277023
  prune: true
  sourceRef:
    kind: GitRepository
    name: "1930740063454277023"
  targetNamespace: default
status: {}
