apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  creationTimestamp: null
  name: kcust3948095059093004433
  namespace: flux-system
spec:
  interval: 5m0s
  path: clusters/provider10+cluster2/context/3948095059093004433
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
status: {}
