apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  creationTimestamp: null
  name: kcust3015338702120886430
  namespace: default
spec:
  interval: 5m0s
  path: clusters/provider10+cluster2/context/3015338702120886430
  prune: true
  sourceRef:
    kind: GitRepository
    name: "3015338702120886430"
  targetNamespace: default
status: {}
