apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  creationTimestamp: null
  name: kcust2375180694632477937
  namespace: default
spec:
  interval: 5m0s
  path: clusters/provider10+cluster2/context/2375180694632477937
  prune: true
  sourceRef:
    kind: GitRepository
    name: "2375180694632477937"
  targetNamespace: default
status: {}
