apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  creationTimestamp: null
  name: kcust6937484790477018568
  namespace: default
spec:
  interval: 5m0s
  path: clusters/provider10+cluster2/context/6937484790477018568
  prune: true
  sourceRef:
    kind: GitRepository
    name: "6937484790477018568"
  targetNamespace: default
status: {}
